rm 3dui-contest.md
rm conferencepapers.md
rm doctoralConsortium.md
rm exhibitors.md
rm journalpapers.md
rm panels.md
rm papers.md
rm posters.md
rm presenterInfo.md
rm researchDemos.md
rm studentVolunteers.md
rm tutorials.md
rm video.md
rm workshoppapers.md
rm workshops.md

touch 3dui-contest.md
touch conferencepapers.md
touch doctoralConsortium.md
touch exhibitors.md
touch journalpapers.md
touch panels.md
touch papers.md
touch posters.md
touch presenterInfo.md
touch researchDemos.md
touch studentVolunteers.md
touch tutorials.md
touch video.md
touch workshoppapers.md
touch workshops.md
